version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: wallos-server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
    
  server:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    volumes:
      - ${APP_DATA_DIR}/data/config/db:/var/www/html/db
      - ${APP_DATA_DIR}/data/config/logos:/var/www/html/images/uploads/logos
    restart: on-failure